// SPDX-License-Identifier: AGPL-3.0-only

package crdversions

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"strings"
	"testing"

	"github.com/prufyx/prufyx/cli/internal/extract"
)

// gzipLiteral is the Go string literal go generate writes for compressed
// bytes ("\x1f\x8b...").
func gzipLiteral(t *testing.T, s string) string {
	t.Helper()
	var b bytes.Buffer
	zw := gzip.NewWriter(&b)
	_, err := zw.Write([]byte(s))
	must(t, err)
	must(t, zw.Close())
	return fmt.Sprintf("%q", b.String())
}

// goCRDs is a generated Go source holding compressed definitions, as
// velero's config/crd/v1/crds/crds.go does.
func goCRDs(lits ...string) string {
	var b strings.Builder
	b.WriteString("// Code generated by crds_generate.go; DO NOT EDIT.\n\npackage crds\n\nimport apiextv1 \"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1\"\n\nvar rawCRDs = [][]byte{\n")
	for _, l := range lits {
		fmt.Fprintf(&b, "\t[]byte(%s),\n", l)
	}
	b.WriteString("}\n\nfunc CRDs() []*apiextv1.CustomResourceDefinition { return nil }\n")
	return b.String()
}

// Review of 2026-10-09 (MED-2): definitions compressed into a Go source
// are read and compared like a YAML file; a literal that cannot be read
// blocks attestation.
func TestGzipLiteralsInGo(t *testing.T) {
	alpha, later := crd("Alpha", "v1beta1", "v1"), crd("Alpha", "v1")
	run := func(from, to string) (extract.PairRecord, PairProof) {
		s := newSynth(
			release{"v1.0.0", map[string]string{"deploy/crds/a.yaml": alpha, "pkg/crds/crds.go": from}},
			release{"v1.1.0", map[string]string{"deploy/crds/a.yaml": later, "pkg/crds/crds.go": to}},
		)
		return pairOf(t, runSynth(t, synthTarget(), s), "1.0.0", "1.1.0")
	}
	finding := func(proof PairProof) *Finding {
		for i, f := range proof.To.Scan.Findings {
			if f.Path == "pkg/crds/crds.go" {
				return &proof.To.Scan.Findings[i]
			}
		}
		return nil
	}
	// The same definitions: a copy, the pair attests.
	p, proof := run(goCRDs(gzipLiteral(t, alpha)), goCRDs(gzipLiteral(t, later)))
	if p.Status != extract.PairDerived || !proof.Completeness.Attestable || finding(proof) != nil {
		t.Fatalf("copy: %s %+v %+v", p.Status, proof.Completeness, proof.To.Scan.Findings)
	}
	var copied bool
	for _, c := range proof.To.Scan.Copies {
		copied = copied || c == "pkg/crds/crds.go"
	}
	if !copied {
		t.Fatalf("not recorded as a copy: %v", proof.To.Scan.Copies)
	}
	// Other served versions: a conflict in the open tree withholds the pair.
	p, _ = run(goCRDs(gzipLiteral(t, alpha)), goCRDs(gzipLiteral(t, alpha)))
	if p.Status != extract.PairWithheld || !strings.Contains(p.Reason, "pkg/crds/crds.go") {
		t.Fatalf("conflict: %s %q", p.Status, p.Reason)
	}
	// A definition the listed paths do not hold: extra.
	_, proof = run(goCRDs(gzipLiteral(t, alpha), gzipLiteral(t, crd("Beta", "v1"))), goCRDs(gzipLiteral(t, later), gzipLiteral(t, crd("Beta", "v1"))))
	if f := finding(proof); f == nil || f.Class != ClassExtra || len(f.CRDs) != 2 || proof.Completeness.Attestable {
		t.Fatalf("extra: %+v %+v", f, proof.Completeness)
	}
	// A corrupt literal, or a compressed definition that is not strictly
	// decodable, is unread: in the open tree it may serve versions the
	// inventory does not show, so the pair is withheld.
	for name, src := range map[string]string{
		"corrupt":      goCRDs(`"\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xffnot gzip"`),
		"undecodable":  goCRDs(gzipLiteral(t, "kind: CustomResourceDefinition\nmetadata: [\n")),
		"second fails": goCRDs(gzipLiteral(t, alpha), `"\x1f\x8b"`),
	} {
		p, _ = run(src, src)
		if p.Status != extract.PairWithheld || !strings.Contains(p.Reason, "pkg/crds/crds.go") {
			t.Errorf("%s: %s %q", name, p.Status, p.Reason)
		}
	}
	// Go sources under a default-excluded directory are not read (NotRead).
	s := newSynth(
		release{"v1.0.0", map[string]string{"deploy/crds/a.yaml": alpha, "test/crds/crds.go": goCRDs(`"\x1f\x8b"`)}},
		release{"v1.1.0", map[string]string{"deploy/crds/a.yaml": later, "test/crds/crds.go": goCRDs(`"\x1f\x8b"`)}},
	)
	if p, proof := pairOf(t, runSynth(t, synthTarget(), s), "1.0.0", "1.1.0"); p.Status != extract.PairDerived || !proof.Completeness.Attestable {
		t.Fatalf("default directory: %s %+v", p.Status, proof.Completeness)
	}
	// Compressed bytes that are not definitions, and a source without any:
	// nothing to record.
	other := goCRDs(gzipLiteral(t, "hello: world\n"))
	_, proof = run(other, goCRDs())
	if f := finding(proof); f != nil || !proof.Completeness.Attestable {
		t.Fatalf("not a definition: %+v %+v", f, proof.Completeness)
	}
}

func TestReadGzipLiteralsBounds(t *testing.T) {
	if g := readGzipLiterals([]byte(`x := "\x1f\x8b"`)); g == nil || g.unread == "" {
		t.Fatalf("truncated: %+v", g)
	}
	if g := readGzipLiterals([]byte("no literal")); g != nil {
		t.Fatalf("none: %+v", g)
	}
	big := gzipLiteral(t, strings.Repeat("a", maxGzipBytes+1))
	if g := readGzipLiterals([]byte(big)); g == nil || !strings.Contains(g.unread, "decompress to more than") {
		t.Fatalf("bound: %+v", g)
	}
	many := strings.Repeat(gzipLiteral(t, "a: 1\n")+"\n", maxGzipLiterals+1)
	if g := readGzipLiterals([]byte(many)); g == nil || !strings.Contains(g.unread, "more than") {
		t.Fatalf("count: %+v", g)
	}
	// Deterministic: the same bytes read twice give the same definitions.
	src := []byte(goCRDs(gzipLiteral(t, crd("Alpha", "v1")), gzipLiteral(t, crd("Beta", "v1"))))
	a, b := readGzipLiterals(src), readGzipLiterals(src)
	if fmt.Sprint(a) != fmt.Sprint(b) || len(a.crds) != 2 {
		t.Fatalf("%+v %+v", a, b)
	}
}
