// SPDX-License-Identifier: AGPL-3.0-only

package factorymirror

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/prufyx/prufyx/cli/internal/maintainer/evidencerepin"
)

// DefaultHost is the host assumed for registry entries written as owner/repo.
const DefaultHost = "github.com"

const (
	maxRegistryBytes int64 = 4 << 20
	maxRulePackBytes int64 = 16 << 20
)

var (
	// ErrInvalid marks malformed caller input (registry, repo names, paths).
	ErrInvalid = errors.New("factory mirror: invalid input")

	hostPattern = regexp.MustCompile(`^[a-z0-9]([a-z0-9.-]{0,251}[a-z0-9])?$`)
	namePattern = regexp.MustCompile(`^[A-Za-z0-9._-]{1,100}$`)
)

// Repo identifies one upstream repository. Components are stored lowercase:
// the supported hosts treat names case-insensitively, and a lowercase key
// keeps the on-disk layout stable on case-insensitive filesystems.
type Repo struct {
	Host  string
	Owner string
	Name  string
}

// Key is the canonical identifier "host/owner/name".
func (r Repo) Key() string { return r.Host + "/" + r.Owner + "/" + r.Name }

// RelPath is the mirror path relative to the state directory.
func (r Repo) RelPath() string {
	return filepath.Join("mirror", r.Host, r.Owner, r.Name+".git")
}

func validName(s string) bool {
	return namePattern.MatchString(s) && s != "." && s != ".." && !strings.HasSuffix(s, ".git")
}

// ParseRepo accepts "owner/name", "host/owner/name" and
// "https://host/owner/name[.git]".
func ParseRepo(s string) (Repo, error) {
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "https://")
	s = strings.TrimSuffix(s, "/")
	s = strings.TrimSuffix(s, ".git")
	parts := strings.Split(s, "/")
	var host, owner, name string
	switch len(parts) {
	case 2:
		host, owner, name = DefaultHost, parts[0], parts[1]
	case 3:
		host, owner, name = parts[0], parts[1], parts[2]
	default:
		return Repo{}, fmt.Errorf("%w: repository %q", ErrInvalid, s)
	}
	host = strings.ToLower(host)
	if !hostPattern.MatchString(host) || !validName(owner) || !validName(name) {
		return Repo{}, fmt.Errorf("%w: repository %q", ErrInvalid, s)
	}
	return Repo{Host: host, Owner: strings.ToLower(owner), Name: strings.ToLower(name)}, nil
}

// RegistrySchema identifies the registry file format.
const RegistrySchema = "prufyx.io/factory-registry/v1"

type registryFile struct {
	Schema string   `yaml:"schema,omitempty"`
	Repos  []string `yaml:"repos"`
}

// LoadRegistry reads a registry file (YAML or JSON) and returns its
// repositories, deduplicated and sorted by key.
func LoadRegistry(path string) ([]Repo, error) {
	raw, err := readBounded(path, maxRegistryBytes)
	if err != nil {
		return nil, err
	}
	return ParseRegistry(raw)
}

// ParseRegistry parses registry bytes. Unknown fields are rejected.
func ParseRegistry(raw []byte) ([]Repo, error) {
	var file registryFile
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	if err := dec.Decode(&file); err != nil && !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("%w: registry: %v", ErrInvalid, err)
	}
	if file.Schema != "" && file.Schema != RegistrySchema {
		return nil, fmt.Errorf("%w: registry schema %q", ErrInvalid, file.Schema)
	}
	var out []Repo
	for _, entry := range file.Repos {
		repo, err := ParseRepo(entry)
		if err != nil {
			return nil, err
		}
		out = append(out, repo)
	}
	return dedupe(out), nil
}

func dedupe(repos []Repo) []Repo {
	seen := map[string]bool{}
	var out []Repo
	for _, r := range repos {
		if !seen[r.Key()] {
			seen[r.Key()] = true
			out = append(out, r)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Key() < out[j].Key() })
	return out
}

// MarshalRegistry renders the registry deterministically.
func MarshalRegistry(repos []Repo) []byte {
	var b bytes.Buffer
	b.WriteString("# Repositories mirrored by the factory mirror worker.\n")
	b.WriteString("# Generated by \"prufyx-maintainer factory registry derive\"; one entry per line,\n")
	b.WriteString("# owner/repo (host defaults to github.com) or host/owner/repo.\n")
	fmt.Fprintf(&b, "schema: %s\nrepos:\n", RegistrySchema)
	for _, r := range dedupe(repos) {
		fmt.Fprintf(&b, "  - %s\n", r.Key())
	}
	return b.Bytes()
}

// DeriveFromRulePacks returns the union of the repositories cited by
// evidence.sources[].url in the given rule packs, plus the repositories in
// each extra registry file. The result is sorted and deduplicated.
func DeriveFromRulePacks(packPaths, extraPaths []string) ([]Repo, error) {
	var all []Repo
	for _, path := range packPaths {
		raw, err := readBounded(path, maxRulePackBytes)
		if err != nil {
			return nil, err
		}
		citations, err := evidencerepin.LoadCitations(path, raw)
		if err != nil {
			return nil, fmt.Errorf("%w: %v", ErrInvalid, err)
		}
		for _, c := range citations {
			repo, err := ParseRepo(DefaultHost + "/" + c.Owner + "/" + c.Repo)
			if err != nil {
				return nil, err
			}
			all = append(all, repo)
		}
	}
	for _, path := range extraPaths {
		repos, err := LoadRegistry(path)
		if err != nil {
			return nil, err
		}
		all = append(all, repos...)
	}
	return dedupe(all), nil
}

// Want asks the mirror command to make one pinned file available offline.
type Want struct {
	Repo   string   `json:"repo"`
	Commit string   `json:"commit"`
	Paths  []string `json:"paths"`
}

// WantsFromRulePacks lists, for every citation in the packs, the repository,
// pinned commit and path whose bytes a later offline step will read.
func WantsFromRulePacks(packPaths []string) ([]Want, error) {
	type key struct{ repo, commit string }
	groups := map[key]map[string]bool{}
	for _, path := range packPaths {
		raw, err := readBounded(path, maxRulePackBytes)
		if err != nil {
			return nil, err
		}
		citations, err := evidencerepin.LoadCitations(path, raw)
		if err != nil {
			return nil, fmt.Errorf("%w: %v", ErrInvalid, err)
		}
		for _, c := range citations {
			repo, err := ParseRepo(DefaultHost + "/" + c.Owner + "/" + c.Repo)
			if err != nil {
				return nil, err
			}
			k := key{repo.Key(), c.OldCommit}
			if groups[k] == nil {
				groups[k] = map[string]bool{}
			}
			groups[k][c.Path] = true
		}
	}
	var out []Want
	for k, paths := range groups {
		w := Want{Repo: k.repo, Commit: k.commit}
		for p := range paths {
			w.Paths = append(w.Paths, p)
		}
		sort.Strings(w.Paths)
		out = append(out, w)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Repo != out[j].Repo {
			return out[i].Repo < out[j].Repo
		}
		return out[i].Commit < out[j].Commit
	})
	return out, nil
}

func readBounded(path string, limit int64) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalid, err)
	}
	defer f.Close()
	raw, err := io.ReadAll(io.LimitReader(f, limit+1))
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalid, err)
	}
	if int64(len(raw)) > limit {
		return nil, fmt.Errorf("%w: %s exceeds %d bytes", ErrInvalid, filepath.Base(path), limit)
	}
	return raw, nil
}
