// SPDX-License-Identifier: AGPL-3.0-only

//go:build prufyx_synthetic_knowledge

package communityapp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/prufyx/prufyx/cli/internal/cncfcheck"
	"github.com/prufyx/prufyx/cli/internal/extract"
	"github.com/prufyx/prufyx/cli/internal/extract/k8sservedapis"
)

// Run with: go test -tags prufyx_synthetic_knowledge -run Synthetic ./internal/communityapp/ (as CI does)
//
// The served-API removal extractor runs over a synthetic Kubernetes tree
// (v1.32.0 to v1.37.0) whose lifecycle declarations and OpenAPI
// specifications remove the API versions of the 1.37 line (1.33 and 1.34 are published). The rules it derives are loaded as synthetic, never published
// knowledge, with no extra fact definition (the build registers the facts),
// and the Kubernetes rendered apply-set route of check cncf is run end to end
// against them.

// servedRemoval is one removal of the synthetic tree.
type servedRemoval struct {
	dir, group string
	line       int
	kinds      []string
	fact       string
}

var servedRemovals = []servedRemoval{
	{"networking", "networking.k8s.io", 37, []string{"IPAddress", "ServiceCIDR"}, "component.kubernetes.ipaddress_servicecidr_v1beta1_removed_gvk_present"},
	{"storage", "storage.k8s.io", 37, []string{"VolumeAttributesClass"}, "component.kubernetes.volumeattributesclass_v1beta1_removed_gvk_present"},
}

func servedCommit(minor int) string {
	return fmt.Sprintf("%040d", 1000+minor)
}

func writeServedFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// servedFixture writes the synthetic tree and returns its root.
func servedFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	repo := filepath.Join(root, "github.com", "kubernetes", "kubernetes")
	tags := map[string]string{}
	for minor := 32; minor <= 37; minor++ {
		tags[fmt.Sprintf("v1.%d.0", minor)] = servedCommit(minor)
		dir := filepath.Join(repo, "commits", servedCommit(minor))
		type gvk struct {
			Group   string `json:"group"`
			Version string `json:"version"`
			Kind    string `json:"kind"`
		}
		definitions := map[string]map[string][]gvk{"io.k8s.api.core.v1.Pod": {"x-kubernetes-group-version-kind": {{"", "v1", "Pod"}}}}
		for _, removal := range servedRemovals {
			api := filepath.Join(dir, "staging", "src", "k8s.io", "api", removal.dir, "v1beta1")
			writeServedFile(t, filepath.Join(api, "register.go"), "package v1beta1\n\nconst GroupName = \""+removal.group+"\"\n")
			lifecycle := "// Code generated by prerelease-lifecycle-gen. DO NOT EDIT.\n\npackage v1beta1\n"
			for _, kind := range removal.kinds {
				lifecycle += fmt.Sprintf("\nfunc (in *%s) APILifecycleRemoved() (major, minor int) {\n\treturn 1, %d\n}\n", kind, removal.line)
				definitions["io.k8s.api."+removal.dir+".v1."+kind] = map[string][]gvk{"x-kubernetes-group-version-kind": {{removal.group, "v1", kind}}}
				if minor < removal.line {
					definitions["io.k8s.api."+removal.dir+".v1beta1."+kind] = map[string][]gvk{"x-kubernetes-group-version-kind": {{removal.group, "v1beta1", kind}}}
				}
			}
			writeServedFile(t, filepath.Join(api, "zz_generated.prerelease-lifecycle.go"), lifecycle)
		}
		writeServedFile(t, filepath.Join(dir, "staging", "src", "k8s.io", "apiextensions-apiserver", "pkg", "apis", "apiextensions", "v1", "register.go"), "package v1\n\nconst GroupName = \"apiextensions.k8s.io\"\n")
		writeServedFile(t, filepath.Join(dir, "staging", "src", "k8s.io", "kube-aggregator", "pkg", "apis", "apiregistration", "v1", "register.go"), "package v1\n\nconst GroupName = \"apiregistration.k8s.io\"\n")
		spec, err := json.MarshalIndent(map[string]any{"swagger": "2.0", "definitions": definitions}, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		writeServedFile(t, filepath.Join(dir, "api", "openapi-spec", "swagger.json"), string(spec)+"\n")
	}
	raw, err := json.Marshal(tags)
	if err != nil {
		t.Fatal(err)
	}
	writeServedFile(t, filepath.Join(repo, "tags.json"), string(raw)+"\n")
	return root
}

// useServedAPIKnowledge derives the rules and loads them; it returns the
// rule id per fact.
func useServedAPIKnowledge(t *testing.T) map[string]string {
	t.Helper()
	repo, err := extract.ParseRepo(k8sservedapis.Repo)
	if err != nil {
		t.Fatal(err)
	}
	src := extract.FixtureReader{Root: servedFixture(t)}
	out, err := extract.Run(context.Background(), k8sservedapis.New(0), src, src, extract.Options{Repo: repo, DerivedAt: time.Date(2026, 10, 4, 0, 0, 0, 0, time.UTC)})
	if err != nil {
		t.Fatal(err)
	}
	raw, err := extract.Canonical(out.Entries)
	if err != nil {
		t.Fatal(err)
	}
	var entries []cncfcheck.Entry
	if err := json.Unmarshal(raw, &entries); err != nil {
		t.Fatal(err)
	}
	ids := map[string]string{}
	for _, entry := range entries {
		var rule struct {
			ID        string `json:"id"`
			Condition struct {
				FactID string `json:"factId"`
			} `json:"condition"`
		}
		if err := json.Unmarshal(entry.Rule, &rule); err != nil {
			t.Fatal(err)
		}
		ids[rule.Condition.FactID] = rule.ID
	}
	if len(entries) != len(servedRemovals) || len(ids) != len(servedRemovals) {
		t.Fatalf("derived %d rules over %v", len(entries), ids)
	}
	for _, removal := range servedRemovals {
		if ids[removal.fact] == "" {
			t.Fatalf("no derived rule over %s: %v", removal.fact, ids)
		}
	}
	// No fact definition is added: the build registers the facts.
	restore, err := cncfcheck.UseSyntheticKnowledge(nil, entries)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(restore)
	return ids
}

func servedObject(api, kind string) string {
	return `{"apiVersion":"` + api + `","kind":"` + kind + `","metadata":{"name":"private-name","namespace":"private-ns"}}`
}

func TestSyntheticServedAPIRemovalCheckWithDerivedRules(t *testing.T) {
	ids := useServedAPIKnowledge(t)
	configMap := servedObject("v1", "ConfigMap")
	for _, removal := range servedRemovals {
		from, to := fmt.Sprintf("1.%d.0", removal.line-1), fmt.Sprintf("1.%d.0", removal.line)
		for _, kind := range removal.kinds {
			removed, served, unreviewed := servedObject(removal.group+"/v1beta1", kind), servedObject(removal.group+"/v1", kind), servedObject(removal.group+"/v1alpha1", kind)
			for _, tc := range []struct {
				name     string
				items    []string
				from, to string
				complete bool
				exit     int
				status   string
			}{
				{"removed version blocks", []string{configMap, removed}, from, to, true, ExitBlocked, "BLOCKED"},
				{"removed version blocks between patches", []string{removed}, fmt.Sprintf("1.%d.4", removal.line-1), fmt.Sprintf("1.%d.2", removal.line), true, ExitBlocked, "BLOCKED"},
				{"served version passes", []string{served, configMap}, from, to, true, 0, "PASS"},
				{"served version passes between patches", []string{served}, fmt.Sprintf("1.%d.9", removal.line-1), fmt.Sprintf("1.%d.1", removal.line), true, 0, "PASS"},
				{"unreviewed version is unknown", []string{unreviewed}, from, to, true, ExitUnknown, "UNKNOWN"},
				{"incomplete scope is unknown", []string{removed}, from, to, false, ExitUnknown, "UNKNOWN"},
			} {
				t.Run(removal.fact+"/"+kind+"/"+tc.name, func(t *testing.T) {
					path := writeCNCFFile(t, "applyset.json", []byte(`{"apiVersion":"v1","kind":"List","items":[`+strings.Join(tc.items, ",")+`]}`), 0o600)
					args := []string{"check", "cncf", "--project", "kubernetes", "--native-resource", path, "--from", tc.from, "--to", tc.to, "--distribution", "official_upstream", "--target-api-apply-required", "--now", "2026-10-05T00:00:00Z", "--format", "json"}
					if tc.complete {
						args = append(args, "--resource-scope-complete")
					}
					code, stdout, stderr := runCNCFCLI(t, args...)
					if code != tc.exit || stderr != "" || strings.Contains(stdout, "private-") {
						t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
					}
					var report cncfcheck.Report
					if err := json.Unmarshal([]byte(stdout), &report); err != nil {
						t.Fatal(err)
					}
					if report.KnowledgeRevision != "synthetic-test-only" {
						t.Fatalf("revision %s", report.KnowledgeRevision)
					}
					// Exactly the derived rules of this line decide; no
					// other claim is decided.
					want := map[string]bool{}
					for _, other := range servedRemovals {
						if other.line == removal.line {
							want[ids[other.fact]] = true
						}
					}
					var got []string
					for _, claim := range report.Check.Claims {
						if claim.RuleID == ids[removal.fact] {
							if claim.Status != tc.status {
								t.Fatalf("%s: %s, want %s", claim.RuleID, claim.Status, tc.status)
							}
						} else if want[claim.RuleID] {
							// The other removal of the same line: its kinds
							// are absent, so it passes with a complete scope.
							if tc.complete && tc.status != "UNKNOWN" && claim.Status != "PASS" {
								t.Fatalf("%s: %s", claim.RuleID, claim.Status)
							}
						} else if claim.Status == "PASS" || claim.Status == "BLOCKED" {
							t.Fatalf("claim of rule %s decided %s", claim.RuleID, claim.Status)
						}
						got = append(got, claim.RuleID)
					}
					sort.Strings(got)
					var wantIDs []string
					for id := range want {
						wantIDs = append(wantIDs, id)
					}
					sort.Strings(wantIDs)
					if strings.Join(got, ",") != strings.Join(wantIDs, ",") {
						t.Fatalf("claims %v, want %v", got, wantIDs)
					}
				})
			}
		}
	}
	// A transition that crosses none of these lines is not decided by them.
	path := writeCNCFFile(t, "applyset.json", []byte(`{"apiVersion":"v1","kind":"List","items":[`+servedObject("storage.k8s.io/v1beta1", "VolumeAttributesClass")+`]}`), 0o600)
	code, stdout, _ := runCNCFCLI(t, "check", "cncf", "--project", "kubernetes", "--native-resource", path, "--from", "1.37.0", "--to", "1.38.0", "--distribution", "official_upstream", "--target-api-apply-required", "--resource-scope-complete", "--now", "2026-10-05T00:00:00Z", "--format", "json")
	if code != ExitUnknown || strings.Contains(stdout, `"BLOCKED"`) || strings.Contains(stdout, `"PASS"`) {
		t.Fatalf("1.37 -> 1.38: code=%d %s", code, stdout)
	}
	// Human output names the blocking rule and the fix.
	path = writeCNCFFile(t, "applyset.json", []byte(`{"apiVersion":"v1","kind":"List","items":[`+servedObject("networking.k8s.io/v1beta1", "ServiceCIDR")+`]}`), 0o600)
	code, stdout, _ = runCNCFCLI(t, "check", "cncf", "--project", "kubernetes", "--native-resource", path, "--from", "1.36.0", "--to", "1.37.0", "--distribution", "official_upstream", "--target-api-apply-required", "--resource-scope-complete", "--now", "2026-10-05T00:00:00Z")
	if code != ExitBlocked || !strings.Contains(stdout, ids["component.kubernetes.ipaddress_servicecidr_v1beta1_removed_gvk_present"]) || !strings.Contains(stdout, "networking.k8s.io/v1") {
		t.Fatalf("code=%d %q", code, stdout)
	}
}
