// SPDX-License-Identifier: AGPL-3.0-only

package cncfcheck

import "github.com/prufyx/prufyx/cli/internal/constraintengine"

const PolicyDeclaration = "Prufyx CNCF source-constraint preview v1: exact declared current/proposed endpoints; compiled minimized facts; scoped PASS/BLOCKED/UNKNOWN; all whole-upgrade assessments UNKNOWN; no runtime, signature, observed input, or upload authority. Maintainer source reviews expire after 90 days; this is not an upstream support lifetime."

// compiledDefinitions is the fact registry of this build: the packaged
// definitions, plus nothing in every shipped build (see
// additionalDefinitions).
func compiledDefinitions() []constraintengine.FactDefinition {
	return append(packagedDefinitions(), additionalDefinitions()...)
}

// packagedDefinitions are the reviewed fact definitions, followed by one
// custom-resource version set per project of the reviewed custom-resource
// table (customResourceVersionDefinitions).
func packagedDefinitions() []constraintengine.FactDefinition {
	return append([]constraintengine.FactDefinition{
		{ID: "component.argo_cd.disable_fine_grained_inheritance", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.argo_cd.latest_distribution", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.argo_cd.latest_execution_surface", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactEnum, EnumTokens: []string{"other", "repository_secret"}},
		{ID: "component.argo_cd.plain_http_oci_repository_unusable", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.argo_cd.repository_settings_complete_and_precedence_resolved", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.argo_cd.requires_inherited_application_permissions", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.argo_cd.requires_v2_visibility_of_v3_default_excluded_resources", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.argo_cd.resource_exclusions_source_default_selected", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.argo_cd.selected_repository_uses_plain_http", Component: "pkg:github/argoproj/argo-cd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.buildpacks.lifecycle_supports_selected_platform_api", Component: "pkg:oci/buildpacksio/lifecycle", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.buildpacks.selected_platform_api", Component: "pkg:oci/buildpacksio/lifecycle", Type: constraintengine.FactEnum, EnumTokens: []string{"0.11", "0.12", "0.13"}},
		{ID: "component.cilium.nonempty_requires_fields", Component: "pkg:github/cilium/cilium", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.cilium.invalid_effective_cluster_name", Component: "pkg:github/cilium/cilium", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.cni_spec.configuration_shape", Component: "pkg:generic/cni-configuration-spec", Type: constraintengine.FactEnum, EnumTokens: []string{"plugin_list", "single_plugin"}},
		{ID: "component.cni_spec.configuration_spec_migration_planned", Component: "pkg:generic/cni-configuration-spec", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.cni_spec.inspected_spec_version", Component: "pkg:generic/cni-configuration-spec", Type: constraintengine.FactEnum, EnumTokens: []string{"0.4.0", "1.0.0"}},
		{ID: "component.containerd.cri_api", Component: "pkg:github/containerd/containerd", Type: constraintengine.FactEnum, EnumTokens: []string{"v1", "v1alpha2"}},
		{ID: "component.containerd.official_bundled_runtimes_only", Component: "pkg:github/containerd/containerd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.containerd.official_upstream_distribution", Component: "pkg:github/containerd/containerd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.containerd.selected_runtime_uses_removed_official_shim", Component: "pkg:github/containerd/containerd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.coredns.distribution", Component: "pkg:github/coredns/coredns", Type: constraintengine.FactEnum, EnumTokens: []string{"custom", "official"}},
		{ID: "component.coredns.federation_directive_present", Component: "pkg:github/coredns/coredns", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.crio.artifact_named_reference_is_short", Component: "pkg:github/cri-o/cri-o", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.crio.artifact_named_reference_resolution_planned", Component: "pkg:github/cri-o/cri-o", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.distribution.image_manifest_format", Component: "pkg:github/distribution/distribution", Type: constraintengine.FactEnum, EnumTokens: []string{"docker_schema1", "docker_schema2", "oci_image_manifest"}},
		{ID: "component.cortex.distribution", Component: "pkg:github/cortexproject/cortex", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.cortex.execution_surface", Component: "pkg:github/cortexproject/cortex", Type: constraintengine.FactEnum, EnumTokens: []string{"cortex", "other"}},
		{ID: "component.cortex.removed_at_modifier_flag_present", Component: "pkg:github/cortexproject/cortex", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.dragonfly.debug_logging_enabled", Component: "pkg:github/dragonflyoss/dragonfly", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.dragonfly.distribution", Component: "pkg:github/dragonflyoss/dragonfly", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.dragonfly.execution_surface", Component: "pkg:github/dragonflyoss/dragonfly", Type: constraintengine.FactEnum, EnumTokens: []string{"manager_config", "other", "scheduler_config"}},
		{ID: "component.dragonfly.legacy_verbose_debug_intent", Component: "pkg:github/dragonflyoss/dragonfly", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.dragonfly.retain_debug_logging_required", Component: "pkg:github/dragonflyoss/dragonfly", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.crossplane.composition_mode", Component: "pkg:github/crossplane/crossplane", Type: constraintengine.FactEnum, EnumTokens: []string{"pipeline", "resources"}},
		{ID: "component.crossplane.distribution", Component: "pkg:github/crossplane/crossplane", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.crossplane.schema_validation_required", Component: "pkg:github/crossplane/crossplane", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.cubefs.metanode_upgrade_phase", Component: "pkg:github/cubefs/cubefs", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.cubefs.raft_sync_snapshot_format_zero", Component: "pkg:github/cubefs/cubefs", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.contour.gateway_v1alpha1_present", Component: "pkg:github/projectcontour/contour", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.cloudnativepg.cluster_reference_changed", Component: "pkg:github/cloudnative-pg/cloudnative-pg", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.cloud_custodian.iam_access_key_json_diff_present", Component: "pkg:github/cloud-custodian/cloud-custodian", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.dapr.scheduler_embedded_etcd_inventory_complete", Component: "pkg:github/dapr/dapr", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.dapr.scheduler_persisted_data_present", Component: "pkg:github/dapr/dapr", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.envoy.xds_api_major", Component: "pkg:github/envoyproxy/envoy", Type: constraintengine.FactEnum, EnumTokens: []string{"v2", "v3"}},
		{ID: "component.etcd.experimental_flags_present", Component: "pkg:github/etcd-io/etcd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.etcd.removed_v2_proxy_flags_present", Component: "pkg:github/etcd-io/etcd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.emissary.removed_metrics_endpoint_present", Component: "pkg:github/emissary-ingress/emissary", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.falco.distribution", Component: "pkg:github/falcosecurity/falco", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.falco.execution_surface", Component: "pkg:github/falcosecurity/falco", Type: constraintengine.FactEnum, EnumTokens: []string{"falco", "other"}},
		{ID: "component.falco.removed_040_cli_flags_present", Component: "pkg:github/falcosecurity/falco", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.fluentd.distribution", Component: "pkg:github/fluent/fluentd", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.fluentd.literal_treatment_change_risk", Component: "pkg:github/fluent/fluentd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.fluentd.selected_value_complete", Component: "pkg:github/fluent/fluentd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.fluentd.current_default_used", Component: "pkg:github/fluent/fluentd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.fluentd.preserve_literal_treatment", Component: "pkg:github/fluent/fluentd", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.flux.removed_beta_api_present", Component: "pkg:github/fluxcd/flux2", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.flux.latest_removed_beta_api_present", Component: "pkg:github/fluxcd/flux2", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.harbor.deployment_mode", Component: "pkg:github/goharbor/harbor", Type: constraintengine.FactEnum, EnumTokens: []string{"custom", "docker-compose", "helm"}},
		{ID: "component.harbor.installer_config_format", Component: "pkg:github/goharbor/harbor", Type: constraintengine.FactEnum, EnumTokens: []string{"cfg", "yml"}},
		{ID: "component.harbor.installer_with_chartmuseum_present", Component: "pkg:github/goharbor/harbor", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.helm.post_renderer_mode", Component: "pkg:github/helm/helm", Type: constraintengine.FactEnum, EnumTokens: []string{"executable_path", "plugin_name", "unset"}},
		{ID: "component.istio.compatibility_profile", Component: "pkg:github/istio/istio", Type: constraintengine.FactEnum, EnumTokens: []string{"1.20", "other", "unset"}},
		{ID: "component.in_toto.in_toto_run_key_argument", Component: "pkg:github/in-toto/in-toto", Type: constraintengine.FactEnum, EnumTokens: []string{"legacy_key", "signing_key"}},
		{ID: "component.jaeger.explicit_config_provided", Component: "pkg:github/jaegertracing/jaeger", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.jaeger.non_memory_storage_required", Component: "pkg:github/jaegertracing/jaeger", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.jaeger.official_jaeger_distribution", Component: "pkg:github/jaegertracing/jaeger", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.keycloak.client_allow_oidc_params_in_redirect_uris", Component: "pkg:github/keycloak/keycloak", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.keycloak.oidc_response_parameter_in_redirect_fragment", Component: "pkg:github/keycloak/keycloak", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.keycloak.server_allow_oidc_params_in_redirect_uris", Component: "pkg:github/keycloak/keycloak", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.karmada.distribution", Component: "pkg:github/karmada-io/karmada", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.karmada.execution_surface", Component: "pkg:github/karmada-io/karmada", Type: constraintengine.FactEnum, EnumTokens: []string{"karmada_policy_application_failover", "other"}},
		{ID: "component.karmada.removed_application_purge_mode_present", Component: "pkg:github/karmada-io/karmada", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.karmada.target_policy_crd_admission_required", Component: "pkg:github/karmada-io/karmada", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.keda.external_scaler_present", Component: "pkg:github/kedacore/keda", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.keda.legacy_tls_cert_file_required_for_transport", Component: "pkg:github/kedacore/keda", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.in_tree_dockershim_required", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.flowcontrol_v1beta3_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.admissionwebhook_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.apiservice_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.crd_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.csr_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.ingress_extensions_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.ingress_networking_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.ingressclass_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.lease_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.priorityclass_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.rbac_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.storage_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.subjectaccessreview_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.tokenreview_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.cronjob_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.csistoragecapacity_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.endpointslice_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.event_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.flowcontrol_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.flowcontrol_v1beta2_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.hpa_v2beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.hpa_v2beta2_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.pdb_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.psp_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.runtimeclass_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.selfsubjectreview_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.validatingadmissionpolicy_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.ipaddress_servicecidr_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.volumeattributesclass_v1beta1_removed_gvk_present", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubernetes.kubelet_version_skew_unsupported_for_target", Component: "pkg:github/kubernetes/kubernetes", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubeedge.distribution", Component: "pkg:github/kubeedge/kubeedge", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.kubeedge.effective_argv_complete", Component: "pkg:github/kubeedge/kubeedge", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubeedge.execution_surface", Component: "pkg:github/kubeedge/kubeedge", Type: constraintengine.FactEnum, EnumTokens: []string{"keadm_init", "other"}},
		{ID: "component.kubeedge.init_version_selection_form", Component: "pkg:github/kubeedge/kubeedge", Type: constraintengine.FactEnum, EnumTokens: []string{"kubeedge_version_flag_only", "legacy_profile_version"}},
		{ID: "component.kubevirt.interface_binding_cardinality_invalid", Component: "pkg:github/kubevirt/kubevirt", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.knative.serving_startup_http_named_port_mismatch", Component: "pkg:github/knative/serving", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kubeflow.kfp_component_authoring_api", Component: "pkg:pypi/kfp", Type: constraintengine.FactEnum, EnumTokens: []string{"dsl_component", "legacy_create_component_from_func"}},
		{ID: "component.kuma.removed_exclude_uid_flags_present", Component: "pkg:github/kumahq/kuma", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.kuma.distribution", Component: "pkg:github/kumahq/kuma", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.kuma.execution_surface", Component: "pkg:github/kumahq/kuma", Type: constraintengine.FactEnum, EnumTokens: []string{"kumactl_install_transparent_proxy", "other"}},
		{ID: "component.kyverno.distribution", Component: "pkg:github/kyverno/kyverno", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.kyverno.execution_surface", Component: "pkg:github/kyverno/kyverno", Type: constraintengine.FactEnum, EnumTokens: []string{"other", "reports_controller"}},
		{ID: "component.kyverno.reports_chunk_size_flag_present", Component: "pkg:github/kyverno/kyverno", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.linkerd.distribution", Component: "pkg:github/linkerd/linkerd2", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.linkerd.execution_surface", Component: "pkg:github/linkerd/linkerd2", Type: constraintengine.FactEnum, EnumTokens: []string{"meshtls_authentication_crd", "other"}},
		{ID: "component.linkerd.mtls_identity_selector_empty", Component: "pkg:github/linkerd/linkerd2", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.linkerd.schema_validation_required", Component: "pkg:github/linkerd/linkerd2", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.metallb.legacy_configmap_present", Component: "pkg:github/metallb/metallb", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.nats.selected_name_has_ascii_space", Component: "pkg:github/nats-io/nats-server", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.longhorn.upgrade_path_check_enabled", Component: "pkg:github/longhorn/longhorn", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opa.modules_use_rego_v1_import", Component: "pkg:github/open-policy-agent/opa", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opa.producer_v0_compatible", Component: "pkg:github/open-policy-agent/opa", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opa.v0_consumers_remain", Component: "pkg:github/open-policy-agent/opa", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opencost.current_cloud_cost_enabled", Component: "pkg:github/opencost/opencost", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opencost.current_provider_derived_source_selected", Component: "pkg:github/opencost/opencost", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opencost.current_source_selection_complete", Component: "pkg:github/opencost/opencost", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opencost.proposed_cloud_cost_enabled", Component: "pkg:github/opencost/opencost", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opencost.proposed_source_selection_complete", Component: "pkg:github/opencost/opencost", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opencost.target_cloud_integration_source_selected_and_declared_present", Component: "pkg:github/opencost/opencost", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opentelemetry.distribution", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactEnum, EnumTokens: []string{"custom", "official"}},
		{ID: "component.opentelemetry.logging_exporter_present", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opentelemetry.internal_metrics_override_absent", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opentelemetry.telemetry_use_localhost_default_metrics_address_effective", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opentelemetry.internal_metrics_remote_scrape_required", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opentelemetry.internal_metrics_localhost_remote_conflict", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opentelemetry.config_complete", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.opentelemetry.config_precedence_resolved", Component: "pkg:github/open-telemetry/opentelemetry-collector", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.openfga.oidc_required_fields_missing", Component: "pkg:github/openfga/openfga", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.prometheus.alertmanager_api_version_selection", Component: "pkg:github/prometheus/prometheus", Type: constraintengine.FactEnum, EnumTokens: []string{"omitted_default_v2", "v1", "v2"}},
		{ID: "component.prometheus.remote_write_enable_http2", Component: "pkg:github/prometheus/prometheus", Type: constraintengine.FactEnum, EnumTokens: []string{"false", "omitted", "true"}},
		{ID: "component.prometheus.remote_write_http2_requirement_unsatisfied", Component: "pkg:github/prometheus/prometheus", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.prometheus.scrape_classic_histograms_key", Component: "pkg:github/prometheus/prometheus", Type: constraintengine.FactEnum, EnumTokens: []string{"always_scrape_classic_histograms", "scrape_classic_histograms"}},
		{ID: "component.rook.deployment_mode", Component: "pkg:github/rook/rook", Type: constraintengine.FactEnum, EnumTokens: []string{"custom", "helm", "manifests"}},
		{ID: "component.spire.distribution", Component: "pkg:github/spiffe/spire", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.spire.execution_surface", Component: "pkg:github/spiffe/spire", Type: constraintengine.FactEnum, EnumTokens: []string{"other", "spire_server_entry_create"}},
		{ID: "component.spire.removed_entry_ttl_flag_present", Component: "pkg:github/spiffe/spire", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.strimzi.distribution", Component: "pkg:github/strimzi/strimzi-kafka-operator", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.strimzi.execution_surface", Component: "pkg:github/strimzi/strimzi-kafka-operator", Type: constraintengine.FactEnum, EnumTokens: []string{"kafka_custom_resource", "other"}},
		{ID: "component.strimzi.kafka_v1beta2_api_present", Component: "pkg:github/strimzi/strimzi-kafka-operator", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.strimzi.target_kafka_crd_admission_required", Component: "pkg:github/strimzi/strimzi-kafka-operator", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.thanos.removed_subcommand_flags_present", Component: "pkg:github/thanos-io/thanos", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.tekton.config_observability_identity_bound", Component: "pkg:github/tektoncd/pipeline", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.tekton.distribution", Component: "pkg:github/tektoncd/pipeline", Type: constraintengine.FactEnum, EnumTokens: []string{"custom_build", "official_upstream"}},
		{ID: "component.tekton.proposed_config_observability_complete_effective", Component: "pkg:github/tektoncd/pipeline", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.tekton.proposed_metrics_protocol_prometheus", Component: "pkg:github/tektoncd/pipeline", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.tekton.retain_prometheus_metrics_required", Component: "pkg:github/tektoncd/pipeline", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.tuf.updater_bootstrap_keyword_present", Component: "pkg:github/theupdateframework/python-tuf", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.velero.crd_update_before_server", Component: "pkg:github/velero-io/velero", Type: constraintengine.FactBool, EnumTokens: nil},
		{ID: "component.vitess.multi_statement_execute_fetch_as_dba", Component: "pkg:github/vitessio/vitess", Type: constraintengine.FactBool, EnumTokens: nil},
	}, customResourceVersionDefinitions()...)
}

func compiledRegistry() (constraintengine.Registry, error) {
	return constraintengine.NewCompiledRegistry(compiledDefinitions())
}
